baseURL = 'http://islanderpr.com/'
languageCode = 'en-us'
title = 'Islander PR'
theme= "dream"



[params]
  background = "#fff"
  backgroundImage = "/img/cover1.jpg"
  linkColor = "seagreen"
  headerTitle = "Puerto Rico"
  favicon = "/img/favicon.ico"


[params.advanced]
  customCSS = ["css/custom.css"]




 
