baseURL = 'http://islanderpr.com/'
languageCode = 'en-us'
title = 'Islander PR'
theme= "dream"

favicon = "/favicon.ico"

[params]
  background = "#fff"
  backgroundImage = "/img/cover1.jpg"
  linkColor = "seagreen"
  headerTitle = "Puerto Rico"


[params.advanced]
  customCSS = ["css/custom.css"]




 
